server:
  port: 9002
spring:
  application:
    name: store-upload
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
aliyun:
  accessKeyId: LTAIhThFc
  accessKeySecret: Xhss9NQEDzY2LZcHfcRXPlJaVYlyc
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    bucketName: chenshiyan
    folder: images1/
