server:
  port: 9001
spring:
  application:
    name: store-item
  datasource:
    url: jdbc:mysql://192.168.25.120:3306/store
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
